## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW2_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}
import numpy as np
import pandas as pd

In [ ]:
# Type your solution here
# Q1-1
df = pd.DataFrame(data)
print(df)

# Q1-2
print("\n")
q2 = df.loc[df.num_cars>df.family_size],["psychologist", "teacher"]
print(q2)

# Q1-3
print("\n")
q3 = df[df.family_size <= 2],[df.num_cars >= 1]
print(q3)

# Q1-4
print("\n")
q4 = len(set(df.job))
print("Num of unique jobs:", q4)

     name                 job  family_size  num_cars
0  Joseph             teacher            3         3
1   Jacob        psychologist            2         1
2     Sam      data scientist            1         1
3   Jesee  software developer            4         2
4    Ryan        psychologist            2         2
5    Lisa        psychologist            3         4
6     Lee             teacher            2         1


(   name           job  family_size  num_cars
5  Lisa  psychologist            3         4, ['psychologist', 'teacher'])


(    name             job  family_size  num_cars
1  Jacob    psychologist            2         1
2    Sam  data scientist            1         1
4   Ryan    psychologist            2         2
6    Lee         teacher            2         1, [0    True
1    True
2    True
3    True
4    True
5    True
6    True
Name: num_cars, dtype: bool])


Num of unique jobs 4


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [ ]:
fruitDic = {"apple":[], "banana":[], "carrot":[]}
for i in range(10):
  if fruit[i] == "apple":
    fruitDic["apple"].append(weights[i])
  elif fruit[i] == "banana":
    fruitDic["banana"].append(weights[i])
  elif fruit[i] == "carrot":
    fruitDic["carrot"].append(weights[i])

# now i have a dictionary with all each fruit as a key, and all the weights as values in a list
print(fruitDic)

# so find the mean for each fruit's values
for key in fruitDic: 
  mean = np.mean(fruitDic[key])
  print(key, "average weight:", mean)
    

{'apple': [5.0, 7.0], 'banana': [2.0, 3.0, 4.0, 6.0, 8.0, 9.0, 10.0], 'carrot': [1.0]}
apple average weight: 6.0
banana average weight: 6.0
carrot average weight: 1.0


**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [ ]:
# Q3-1
print("\n")
print(np.where(np.sort(course_name)))

# Q3-2
print("\n")
p = True 
while p == True: 
  for element in course_name:
    if np.char.startswith(element, "P"):
      p = True
    else:
      p = False
print(p)




(array([0, 1, 2, 3, 4]),)


False


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [ ]:
# Q4-1
print("\n")
print(student_id)
print(np.flip(student_id))

# Q4-2
print("\n")
print((np.sort(student_id)[-3:]))




[1023 5202 6230 1671 1682 5241 4532]
[4532 5241 1682 1671 6230 5202 1023]


[5202 5241 6230]


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [ ]:
# Type your solution here
arr = np.arange(100)
multipleOf3 = np.where(arr % 3 == 0)
print("sum of multiples of 3:", np.sum(multipleOf3))

multipleOf5 = np.where(arr % 5 == 0)
print("sum of multiples of 5:", np.sum(multipleOf5))

print("sum of multiples of 3 and 5 below 100:", (np.sum(multipleOf5)+np.sum(multipleOf3)))

sum of multiples of 3: 1683
sum of multiples of 5: 950
sum of multiples of 3 and 5 below 100: 2633


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# Q6-1
arr[:,[1, 2]] = arr[:,[2, 1]]
print(arr)

# Q6-2
print("\n")
arr[[0,1],:] = arr[[1,0],:]
print(arr)

[[ 0  2  1  3]
 [ 4  6  5  7]
 [ 8 10  9 11]]


[[ 4  6  5  7]
 [ 0  2  1  3]
 [ 8 10  9 11]]
